# Generated by Django 3.1.7 on 2021-04-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingreso', models.CharField(max_length=100, null=True)),
                ('valor', models.IntegerField(null=True)),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('tag', models.CharField(choices=[('Fijo', 'Fijo'), ('Extra', 'Extra')], max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
