# Generated by Django 3.1.7 on 2021-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date_created',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date_created',
            field=models.DateField(blank=True),
        ),
    ]
