# Generated by Django 3.1.7 on 2021-05-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210521_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='date_created',
            new_name='date',
        ),
    ]
