# Generated by Django 3.1.7 on 2021-05-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20210521_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Trabajo', 'Trabajo'), ('Mercado', 'Mercado'), ('Servicios', 'Servicios'), ('Entretenimiento', 'Entretenimiento'), ('Ropa', 'Ropa'), ('Deudas', 'Deudas'), ('Regalos', 'Regalos'), ('Otro', 'Otro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='categoria',
            field=models.CharField(choices=[('Trabajo', 'Trabajo'), ('Familia', 'Familia'), ('Otro', 'Otro')], max_length=100, null=True),
        ),
    ]
