# Generated by Django 3.1.7 on 2021-06-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210524_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Trabajo', 'Trabajo'), ('Mercado', 'Mercado'), ('Servicios', 'Servicios'), ('Entretenimiento', 'Entretenimiento'), ('Ropa', 'Ropa'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Transporte', 'Transporte'), ('Educación', 'Educación'), ('Regalos', 'Regalos'), ('Arriendo', 'Arriendo'), ('Otro', 'Otro')], max_length=100, null=True),
        ),
    ]
